### ISSUE TITLE
Issue with updating bookmark

### ISSUE THREAD

**Issue by alexwennerberg** [makeworld-the-better-one/amfora#92] opened 2020-09-18 02:32 UTC
To reproduce:

1. Press ctrl-D to create a bookmark. This works as expected
2. Press ctrl-D to update the bookmark. This works as expected.
3. Press ctrl-D again -- amfora doesn't pull up the update the bookmark prompt, but clears the existing bookmark and pulls up the create bookmark prompt again

**Comment by makeworld-the-better-one** [comment] 2020-09-18 21:38
This appears to be a duplicate of #91. Clicking Change in your step 2 with no actual changes causes the bookmark to be removed, which is why it appears blank in step 3. Thanks though!

**Closed by makeworld-the-better-one** 2020-09-18 21:38 UTC
