### ISSUE TITLE
Shift + Tab doesn't cycle through links in st terminal

### ISSUE THREAD

**Issue by nbonfils** [makeworld-the-better-one/amfora#161] opened 2020-12-27 20:36 UTC
## Description of the issue
I tried the amfora on master (e42b24c6f2ab8adf351ef3c6decde36f970dcd5c as of this writing) and `Shift + Tab` doesn't seem to work at all.
 `Tab` correctly cycles through the links but `Shift + Tab` expected to cycle backwards doesn't work, _nothing happens when I press both keys_.

## Environement
OS: `Linux - NixOS 21.03.20201209.e9158ec (Okapi)`
Terminal emulator: `st`

**Comment by makeworld-the-better-one** [comment] 2020-12-27 21:02
That's strange. I tested just now, from the same commit, and it works fine. I tested both Guake and xfce4-terminal and both worked. Even basic xterm did.

Could it be an issue with st? Could you try using another terminal and see?

**Comment by nbonfils** [comment] 2020-12-27 21:15
Yep, just tried with xfce4-terminal and it worked too.
It seems indeed to be an issue with st... Any clue on how to start debugging this ?
I just started looking into the code trying to find where the `shift + tab` is handled, I don't mind contributing and fixing it myself, just need a few pointers :)
Tried multiple tui gemini browsers those last 2 days and amfora is by far the most to my taste :+1:

**Comment by makeworld-the-better-one** [comment] 2020-12-27 21:43
I suspect this is a bug with `st` and not Amfora at all, so I will close this issue. If it's not a bug with st, it would be a bug with the upstream TUI libraries used, [cview](https://gitlab.com/tslocum/cview/) and [tcell](https://github.com/gdamore/tcell). Out of the two it's likely tcell, as that is the lower-level library that would be handling individual keys. But I still think it's probably st.

One thing you can do to test this problem is to run the command `showkey -a` in st, and see if the terminal can detect Shift+Tab properly. Here are the results of pressing Tab, then the <kbd>a</kbd> key, then Shift+Tab, in Guake. I used <kbd>a</kbd> just as a divider for the other two keys.

```
➤ showkey -a

Press any keys - Ctrl-D will terminate this program

                  9 0011 0x09
a 	     97 0141 0x61
^[[Z 	 27 0033 0x1b
 	     91 0133 0x5b
 	     90 0132 0x5a

```

If you can get the same result, then st is picking up keys fine and you should file a tcell bug. Otherwise, it's probably st.

**Comment by nbonfils** [comment] 2020-12-27 22:22
It seems `st` is picking up the keys:
```
❯ showkey -a

Press any keys - Ctrl-D will terminate this program

a        97 0141 0x61
^[[Z     27 0033 0x1b
         91 0133 0x5b
         90 0132 0x5a
```

Will check with tcell then, thanks, do you mind pointing the relevant bit of code handling `shift + tab` so I can try to reproduce it?

**Comment by nbonfils** [comment] 2020-12-27 22:31
According to https://github.com/gdamore/tcell/issues/309 it seems that it was fixed in v2.0.0 of tcell here: https://github.com/gdamore/tcell/commit/59ebfab322450e8d8c937abd7b5f12eb961b9aed

So since it's already fixed upstream, and current version of tcell is v1.3.0 I propose to reopen this until the version of tcell is bumped to at least v2.0.0.

**Comment by makeworld-the-better-one** [comment] 2020-12-27 23:03
Oh okay, thanks. tcell has been bumped in #137, so once that's merged than this will be fixed. That should happen for v1.8.0.

**Comment by mke21** [comment] 2021-02-02 21:56
Just a comment that the problem seems to exist in the tty as well, at least on my Manjaro installation.

**Closed** 2021-02-17 19:17 UTC
Labels: bug, upstream
