### ISSUE TITLE
Config error keys cannot contain  character

### ISSUE THREAD

**Issue by klundry** [makeworld-the-better-one/amfora#226] opened 2021-04-13 22:37 UTC
All of a sudden when launching amfora it started failing with this error:

"Config error: While parsing config: (1, 1): parsing error: keys cannot contain  character"

That is a blank space in between contain and character. I have nuked my .config/amfora directory and still get the error. Same thing on 1.7.2 and 1.8.0.

I apologize in advance if this is an issue with something borked on my system but I'm not sure where to start finding what could be wrong based on that error message.

**Comment by makeworld-the-better-one** [comment] 2021-04-13 23:14
> I have nuked my .config/amfora directory and still get the error.

I cannot reproduce this, with master or v1.8.0. When I remove the `~/.config/amfora/config.toml` file, it generates a new one and opens fine. Sounds like a problem elsewhere. Can you post the full traceback/output of the error?

**Comment by klundry** [comment] 2021-04-13 23:29
That's what I was afraid of :). I'm using the binary from the releases page and what I pasted in quotes is the only output it gives me. I'm not sure how to do a traceback.

**Comment by makeworld-the-better-one** [comment] 2021-04-13 23:44
That's very strange. Can you delete and try again? And then paste the first line of the generated config, if any? Also give details of your system, like your OS, and architecture.

It shouldn't apply here at all, but Amfora also stores information in `~/.local/share/amfora/` and `~/.cache/amfora/`. You could try deleting those. Let me know if that changes anything.

> I'm not sure how to do a traceback.

My bad, it makes sense there isn't any more than what you pasted.

**Comment by klundry** [comment] 2021-04-13 23:59
Hmm, it was something in .local/share/amfora. I had already deleted .config/amfora and .cache/amfora but I did those again and also .local/share/amfora and now it launches again. 

PS. I'm one an armv7 device running debian buster.

**Comment by makeworld-the-better-one** [comment] 2021-04-14 00:18
Hmm. `~.local/share/amfora/` contains bookmarks and subscriptions. Looks like your `bookmarks.toml` file got messed up. But keys should be able to contain spaces? I'm not sure. Are you able to reliably reproduce this by creating bookmarks or something?

Out of curiousity, what device are you using? From your GitHub profile, I suspect it's a PocketCHIP :)

**Comment by klundry** [comment] 2021-04-14 00:24
Yes, it's the PocketCHIP :D. I had an accidental unclean shutdown before this happened so maybe it corrupted? I don't even use the bookmarks because I keep a links page that I use as my bookmarks on my own capsule.

**Comment by makeworld-the-better-one** [comment] 2021-04-14 00:40
Hmm, maybe. If you can't reproduce the issue let me know, and I'll close the issue.

**Closed** 2021-09-18 15:57 UTC
Labels: question
