### ISSUE TITLE
Does not connect to gemini links from termux

### ISSUE THREAD

**Issue by karlh626** [makeworld-the-better-one/amfora#216] opened 2021-04-06 21:25 UTC
Amfora is my favorite gemini browser and I especially like the subscription feature.

I have noticed that when I try to use amfora from termux it connects to local/internal links but no outside links.

For example, it will connect and display the help and bookmarks I may have added but when I try another gemini link I get and error.

screenshot of the error:
![Screenshot_20210406-161710_Termux](https://user-images.githubusercontent.com/398962/113780143-6542df00-96f4-11eb-9104-4662f15f6a92.jpg)

In the same termux, AV-98 works fine.

From the error, it looks almost like it is trying to connect using IPV6?

I would love to use amfora in termux as well.

Thanks for any ideas or suggestions.

**Comment by makeworld-the-better-one** [comment] 2021-04-06 21:47
Happy to hear you're enjoying Amfora! Using it on termux is cool :)

This is a duplicate of #120. Just run these commands to get it to work:

```
pkg install proot
termux-chroot
amfora
```

I will add these to the README.

**Closed by makeworld-the-better-one** 2021-04-06 21:47 UTC

**Comment by makeworld-the-better-one** [comment] 2021-04-06 21:56
Added to the README in fdbc1d5, see [this section](https://github.com/makeworld-the-better-one/amfora#termux). Let me know if this fix didn't work for you.

**Comment by karlh626** [comment] 2021-04-08 16:13
Thank you very much for your quick response!  Your suggestions worked perfectly and I appreciate your addition to the README
